services:
  # Database Layer
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=omniorder
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # Backend Layer
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    volumes:
      - ./apps/api:/app
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_DB=omniorder
    depends_on:
      - db
      - minio
    ports:
      - "8000:8000"

  # Frontend Layer (Node Dev Server)
  web:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./apps/web:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
  
  # Edge Layer
  nginx:
    image: nginx:alpine
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - web

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # One-time setup to create bucket and set public policy
  # minio-setup:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
  #     /usr/bin/mc mb myminio/omniorder-assets --ignore-existing;
  #     /usr/bin/mc anonymous set download myminio/omniorder-assets;
  #     exit 0;
  #     "

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  #
  # Authentik
  #
  # authentik-server:
  #   image: ghcr.io/goauthentik/server:2025.10.3
  #   command: server
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     AUTHENTIK_REDIS__HOST: redis
  #     AUTHENTIK_POSTGRESQL__HOST: db
  #     AUTHENTIK_POSTGRESQL__NAME: authentik
  #     AUTHENTIK_POSTGRESQL__PASSWORD: postgres
  #     AUTHENTIK_POSTGRESQL__USER: postgres
  #     AUTHENTIK_SECRET_KEY: GNqsFVGOH3/6iDCXemLVppjgW4YzyO2+MXblxMxohoMur8JLKhgpamQGTa5NIery
  #   ports:
  #   - 9002:9000
  #   - 9443:9443
  # authentik-worker:
  #   image: ghcr.io/goauthentik/server:2025.10.3
  #   command: worker
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     AUTHENTIK_POSTGRESQL__HOST: db
  #     AUTHENTIK_POSTGRESQL__NAME: authentik
  #     AUTHENTIK_POSTGRESQL__PASSWORD: postgres
  #     AUTHENTIK_POSTGRESQL__USER: postgres
  #     AUTHENTIK_SECRET_KEY: GNqsFVGOH3/6iDCXemLVppjgW4YzyO2+MXblxMxohoMur8JLKhgpamQGTa5NIery
  #   restart: unless-stopped
  #   user: root
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  minio_data: